spring:
  config:
    activate:
      on-profile: dev

  server:
    port: 8080
    servlet:
      context-path: /warehouse

  datasource:
    url: jdbc:h2:mem:warehouse
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      product-change-availability: product-change-availability-exchange
    queue:
      product-change-availability: product-change-availability-queue
    routing-key:
      product-change-availability: product-change-availability-routing-key
