spring:
  devtools:
    remote:
      secret: 123
    restart:
      trigger-file: trigger.txt

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
